import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import Button from "~/components/ui/Button";
import GameCard from "~/components/games/GameCard";
import GameGrid from "~/components/games/GameGrid";

const Home: NextPage = () => {
  const { data } = api.example.getSecretMessage.useQuery();

  return (
    <>
      <Head>
        <title>The Pit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-2 py-4">
        <section>
          <p>Secret Message: {data}</p>
          <GameGrid></GameGrid>
        </section>
      </div>
    </>
  );
};

export default Home;
